### ISSUE TITLE
CIE: Errori di convalida del metadata

### ISSUE THREAD

**Issue by klu0** [italia/spid-cie-php#203]
Buongiorno,
dopo  l'aggiornamento alla versione 3.16.0 e l'attivazione contestuale di CIE, ho richiesto la convalida
del metadata relativo alla funzione CIE.
Di seguito è riportato lo screenshot dell'errore ricevuto.

![cie_errori_metadata](https://github.com/italia/spid-cie-php/assets/112711606/ddff03f0-e58a-4fcd-a625-a72e0268e9b2)

Grazie

**Comment by klu0** [comment]
Buongiorno, 
con l'aggiornamento alla versione 3.17.0, il link per la creazione del metadata CIE genera errori.
In particolare lo script .../[myservice]/module.php/saml/sp/metadata.php/cie?output=xhtml fa un redirect alla pagina error.php. 

Grazie

**Comment by damikael** [comment]
Risolto con la versione [v.3.17.1](https://github.com/italia/spid-cie-php/releases/tag/v.3.17.1)
