### ISSUE TITLE
Undefined array key "idp" in /home/.../login-spid.php

### ISSUE THREAD

**Issue by paulocoghi** [italia/spid-cie-php#207]
Dopo aver migrato da un server con Ubuntu 20.04 per un Rocky 9.1, con le seguenti caratteristiche, riceviamo l'errore `Undefined array key "idp" in /home/.../login-spid.php`

**Ubuntu 20.04**
PHP 8.0.29
nginx 1.25.1
OpenSSL 1.1.1f  31 Mar 2020

**Rocky 9.1**
PHP 8.0.30
nginx 1.20.1
OpenSSL 3.0.7 1 Nov 2022

Io sospetto che il problema sia nella versione OpenSSL utilizzata, ma vorrei la vostra opinione.

**Comment by damikael** [comment]
Ciao @paulocoghi ,
che versione di spid-cie-php stai utilizzando?

**Comment by paulocoghi** [comment]
Siamo nella `3.16.0` nei due ambienti

**Comment by damikael** [comment]
sul file login-spid.php
generato durante il setup iniziale, provare a modificare la riga corrispondente alla seguente:

https://github.com/italia/spid-cie-php/blob/5dffcb1f21b560955b20f46c99ce4997f3fe7f0a/setup/sdk/login.tpl#L8

con:

`$idp = isset($_REQUEST['idp'])? $_REQUEST['idp'] : null; `

Fammi sapere se tale patch risolve

**Comment by paulocoghi** [comment]
L'errore precedente non compare più, e ora abbiamo questi nuovi errori:

```
2023/09/14 17:36:12 [error] 1210681#1210681: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  session_regenerate_id(): Session ID cannot be regenerated when there is no active session in /home/.../spid-cie-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 164" while reading response header from upstream, client: 93.44.194.25, server: spid.conservatoriocosenza.it, request: "GET /?idp=DEMO HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/webapp.sock:", host: "spid.conservatoriocosenza.it", referrer: "https://spid.conservatoriocosenza.it/"
2023/09/14 17:36:26 [warn] 1210681#1210681: *2 a client request body is buffered to a temporary file /var/lib/nginx/tmp/client_body/0000000001, client: 93.44.194.25, server: spid.conservatoriocosenza.it, request: "POST /spid/module.php/saml/sp/saml2-acs.php/spid HTTP/2.0", host: "spid.conservatoriocosenza.it", referrer: "https://demo.spid.gov.it/"
2023/09/14 17:36:26 [error] 1210681#1210681: *2 FastCGI sent in stderr: "PHP message: PHP Warning:  session_regenerate_id(): Session ID cannot be regenerated when there is no active session in /home/.../spid-cie-php/vendor/simplesamlphp/simplesamlphp/lib/SimpleSAML/SessionHandlerPHP.php on line 164" while reading response header from upstream, client: 93.44.194.25, server: spid.conservatoriocosenza.it, request: "POST /spid/module.php/saml/sp/saml2-acs.php/spid HTTP/2.0", upstream: "fastcgi://unix:/run/php-fpm/webapp.sock:", host: "spid.conservatoriocosenza.it", referrer: "https://demo.spid.gov.it/"
```

**Comment by damikael** [comment]
Provare a cancellare cookie e a verificare i permessi di scrittura in:

**Comment by paulocoghi** [comment]
Stesso errore. Non solo abbiamo cambiato i permessi di questa cartella, come ancora abbiamo provato con un'altra modalità di sessione, in particolare con redis, e l'errore continua lo stesso.

**Comment by damikael** [comment]
Ok, appena riesco cerco di approfondire. Magari prova a verificare anche con il salvataggio delle sessioni su DB SQL.

**Comment by paulocoghi** [comment]
Abbiamo provato la `session.save_path` in diversi modi, non solo con Redis, ma anche con una cartella diversa e con permessi `777`, senza soluzione.

**Comment by damikael** [comment]
Buongiorno @paulocoghi ,

siete poi riusciti a risolvere?

**Comment by paulocoghi** [comment]
Sì. L'azienda responsabile per il (re)deploy aveva problemi di configurazione nel loro server, e il problema non era nella libreria `spid-cie-php`.
