### ISSUE TITLE
Errore  p.iva su metadata spId azienda privata

### ISSUE THREAD

**Issue by fortwo-web** [italia/spid-cie-php#255]
Buongiorno,
un mio cliente vuole attivare spid sulla sua azienda privata.
ho installato la libreria spid-php correttamente sul mio server tramite composer. 

Tramite la modalità "SPID Demo (Validator mode)", ho scaricato il metadata e lo validato con "check strict" correttamente. 

Quando metto "Check per Produzione" ricevo però l'errore sulla p.iva; ho provato a scriverla in tutti i modi:
- IT-012345678901
- 012345678901
- IT012345678901
- VATIT-IT012345678901
- VATIT-IT-012345678901

se inserisco  IT012345678901 ricevo l'errore:
_errore 163 SPID Compliant Certificates Value for name attribute [Unknown OID, 2.5.4.97] must match ^(CF:IT-[a-zA-Z0-9]{16}|VATIT-\d{11})$)_

se inserisco  012345678901 ricevo l'errore
_126 | The VATNumber element MUST start with a valid ISO3166 Code_

dove sbaglio?
Saluti
Luca

**Comment by nicolalazzaro** [comment]
Ciao @fortwo-web, la chiave di configurazione all'interno del file `spid-php-setup.json` che necessita di rispettare la codifica ISO3166 è `spOrganizationCode`. Quindi `spOrganizationCodeType` deve essere `VATNumber`.

**Comment by fortwo-web** [comment]
ottimo grazie!
