### ISSUE TITLE
problema con firma del metadata

### ISSUE THREAD

**Issue by fortwo-web** [italia/spid-cie-php#257]
Buongiorno,
ho ricevuto correttamente il certificato da parte di agid. 
Ho copiato la chiave privata (.pem), il certificato ricevuto (.cert) e il metadata (scaricandolo da ..module.php/saml/sp/metadata.php/spid) nella cartella spid-php. 

Ho eseguito il comando php metadata-signer.php metadata.xml metadata-signed.xml service da ssh. 

Mi viene generato un file che è identico all'originale (uso php 8.2)

Ho saltato qualche passaggio?

grazie
Luca

**Comment by alexlarocca** [comment]
Ciao, parecchi mesi fa ho avuto lo stesso problema ed è causato da una specifica configurazione disabilitata dell'SDK. Adesso non sono in grado di indicare esattamente il file dove questa configurazione è presente. L'avevo anche comunicata a @damikael attraverso Slack ma il messaggio risulta nascosto perchè meno recente di 90 giorni. All'epoca l'ho individuata esaminando direttamente il codice

**Comment by fortwo-web** [comment]
**MA SEI UN GRANDE**! GRAZIE mille Alex! sono riuscito al volo a fare il tutto

**Comment by fortwo-web** [comment]
Ciao, @alexlarocca scusa se approfitto ancora del tuo aiuto..

ho fatto tutto e inviato in validazione, però mi hanno risposto da agid:
"
Per quanto riguarda il metadata:
tutti i certificati all'interno del metadata devono essere rilasciati da AgID
"
non capisco, con la firma del metadata  mi trovo due nodi <signature>, è corretto?

<img width="172" alt="Screenshot 2024-11-08 alle 17 17 41" src="https://github.com/user-attachments/assets/a026f91a-7c28-48e7-8bf5-6c0f0d67c5d8">

**Comment by alexlarocca** [comment]
Dovresti averne solo una. Possibile che hai firmato un metadata già firmato. Da quello generato dall'SDK, prima di firmarlo con il nuovo certificato, hai rimosso la vecchia firma?

**Comment by fortwo-web** [comment]
ecco! no, non ho rimosso la vecchia firma..mi ero perso questo passaggio!
allora semplicemente:
1. mi riscarico il metadata dalla mia applicazione
2. rimuovo il nodo "Signature"
3. firmo il metadata 
e il gioco è fatto!
GRAZIE ancora @alexlarocca gentilissimo, rimando in validazione e speriamo sia la volta buona 👍

**Comment by fortwo-web** [comment]
@alexlarocca grazie per l'aiuto, mi hanno validato la richiesta finalmente! 
per aggiornare il metadata con quello inviato a agid (con il certificato corretto) come devo fare? c'è una guida a riguardo?
